In [14]:
import numpy as np
a= np.array([2,5,7])
type(a)
a.shape


(3,)

# 2-D array using numpy

In [21]:
b=np.array([[2,3],[5,9],[1,7]])
print(b.shape)
b

(3, 2)


array([[2, 3],
       [5, 9],
       [1, 7]])

In [15]:
a[0]=5
a

array([5, 5, 7])

In [23]:
b[1,1]+b[0,1]

12

In [32]:
c=np.array([1,3,2],dtype=float)
c[1:] #slicing the data

array([3., 2.])

In [36]:
print(5 in a)
3*a

True


array([15, 15, 21])

In [37]:
b.fill(2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

# IDENTITY MATRIX

In [38]:
eye=np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
ones1=np.ones(4)
ones2=np.ones((2,3))
zero1=np.zeros((3,5))
print(ones1)
print("\n")
print(ones2)
print("\n")
print(zero1)

[1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# sum, product operations

In [55]:
a.sum()
a.prod()
a.mean()
a.std()# standard deviation

0.9428090415820634

# using arange

In [57]:
n=np.arange(5)
print(n)
print(np.arange(5,10,2))

[0 1 2 3 4]
[5 7 9]


# random function

In [59]:
ran = np.random.rand(5) # print random 5 numbers between 0 and 1. 
ran

array([0.9080703 , 0.14517374, 0.90490456, 0.86713832, 0.42872412])

In [60]:
ran1=np.random.rand(2,3)
ran1

array([[0.11826129, 0.70197251, 0.91756901],
       [0.80627674, 0.13517664, 0.1651439 ]])

In [64]:
ran2=np.random.randint(2,12) # it will give any random int between 2 and 12
ran2

2

# dot product of two arrays

In [65]:
arr1=np.array([3,6,1])
arr2=np.array([1,4,6])
k=np.dot(arr1,arr2)
print(k)

33
